steps:
  - name: 'docker.io/hashicorp/terraform:1.6'
    args: ['init']
    dir: terraform/
  - name: 'docker.io/hashicorp/terraform:1.6'
    args: ['plan', '-var-file=env.tfvars', '-out=tf.tfplan']
    dir: terraform/
  - name: 'docker.io/hashicorp/terraform:1.6'
    args: ['apply', 'tf.tfplan']
    dir: terraform/

logsBucket: 'gs://elegant-pipe-423001-f8-cb-logs'
